### ISSUE TITLE
转发好像没图片

### ISSUE THREAD

**Issue by a1232580** [aiqinxuancai/QinRSS#1]
不知道是不是我水管小
4m宽带
转发好像没图片

**Comment by aiqinxuancai** [comment]
你还能用？我这Nitter的源都炸了，用的老版本的吗

**Comment by a1232580** [comment]
> 你还能用？我这Nitter的源都炸了，用的老版本的吗

啊，不是很懂，不过我用的是v1.0.0
可以正常使用
然后订阅地址是我本地自己的

**Comment by aiqinxuancai** [comment]
我看看，最近twitter的源炸了，所以QinRss没怎么维护

**Comment by a1232580** [comment]
> 我看看，最近twitter的源炸了，所以QinRss没怎么维护

好的，我主要是订阅微博，微博转的好像没图片

**Comment by aiqinxuancai** [comment]
> > 我看看，最近twitter的源炸了，所以QinRss没怎么维护
> 
> 好的，我主要是订阅微博，微博转的好像没图片

已找到原因了，因为微博订阅的图片URL似需要登录态或特定的请求头才可以访问，这样直接Get无法获取到，目前暂时没有办法解决。
https://wx3.sinaimg.cn/orj360/66fd066bly8hnfohq2qsij20vg0pcdjt.jpg

**Comment by a1232580** [comment]
![Screenshot_2024-04-18-18-22-15-48_2665fb67b16260a8d818298cef8dc107](https://github.com/aiqinxuancai/QinRSS/assets/115947952/b0abf6d5-1b8c-4641-96f3-d2afc0d1f37a)
> > > 我看看，最近twitter的源炸了，所以QinRss没怎么维护
> > 
> > 
> > 好的，我主要是订阅微博，微博转的好像没图片
> 
> 已找到原因了，因为微博订阅的图片URL似需要登录态或特定的请求头才可以访问，这样直接Get无法获取到，目前暂时没有办法解决。 https://wx3.sinaimg.cn/orj360/66fd066bly8hnfohq2qsij20vg0pcdjt.jpg

但是正常发微博的图片是能够获取到的
转发的不行
也不知道啥原因
而且我用了新版本之后，发现好像发不出消息
![Screenshot_2024-04-18-18-22-15-48_2665fb67b16260a8d818298cef8dc107](https://github.com/aiqinxuancai/QinRSS/assets/115947952/4fcb2b54-66de-43ad-9502-afa4168dbfbe)

**Comment by aiqinxuancai** [comment]
> ![Screenshot_2024-04-18-18-22-15-48_2665fb67b16260a8d818298cef8dc107](https://private-user-images.githubusercontent.com/115947952/323564068-b0abf6d5-1b8c-4641-96f3-d2afc0d1f37a.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0MzY4ODEsIm5iZiI6MTcxMzQzNjU4MSwicGF0aCI6Ii8xMTU5NDc5NTIvMzIzNTY0MDY4LWIwYWJmNmQ1LTFiOGMtNDY0MS05NmYzLWQyYWZjMGQxZjM3YS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxOFQxMDM2MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZTJkMjA3NTk5ODk1YzU0ZDE5ZGNlOGY2YWU4NTZmOTI0MmRhODBhNzdhYjQ5Zjc3NjIyZWEzYmJkYTc0MGViJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ybiSC434YYj-hfuJci8Xf6G6LP-TwKYQQjritW_yovM)
> 
> > > > 我看看，最近twitter的源炸了，所以QinRss没怎么维护
> > > 
> > > 
> > > 好的，我主要是订阅微博，微博转的好像没图片
> > 
> > 
> > 已找到原因了，因为微博订阅的图片URL似需要登录态或特定的请求头才可以访问，这样直接Get无法获取到，目前暂时没有办法解决。 https://wx3.sinaimg.cn/orj360/66fd066bly8hnfohq2qsij20vg0pcdjt.jpg
> 
> 但是正常发微博的图片是能够获取到的 转发的不行 也不知道啥原因 而且我用了新版本之后，发现好像发不出消息 ![Screenshot_2024-04-18-18-22-15-48_2665fb67b16260a8d818298cef8dc107](https://private-user-images.githubusercontent.com/115947952/323564092-4fcb2b54-66de-43ad-9502-afa4168dbfbe.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0MzY4ODEsIm5iZiI6MTcxMzQzNjU4MSwicGF0aCI6Ii8xMTU5NDc5NTIvMzIzNTY0MDkyLTRmY2IyYjU0LTY2ZGUtNDNhZC05NTAyLWFmYTQxNjhkYmZiZS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxOFQxMDM2MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMDcyZDljN2JiOTQ4ZjE2ZTcxMTU0NWZkZDI3ZDYyZjNkMmYzNGJhYTY3N2U0MjMxNzE3YTk5ZDQ2MjM1MTRiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.WAPV8wO-ufEjcrop_o2PYbwZCZy3Prd3_TPtI8hAP3s)

图片是真的从里面拿到读不出来

发不出去的问题修复了，v1.0.2。
